### ISSUE TITLE
Text default visible

### ISSUE THREAD

**Issue by furukama** [christophergandrud/d3Network#28]
Hi,

thanks for the great package! I was wondering whether it was possible to make the node labels visible per default (and maybe customize the font). Is there a way to do this?

Best
Benedikt

**Comment by christophergandrud** [comment]
`d3SimpleNetwork` will show the the labels by default. For `d3ForceNetwork` you'll need to actually change the JavaScript in the output file. (I think you can just delete the stuff about `moustover` and `mouseout` for text. 

Fonts should be customisable via the regular CSS in the output document.
