### ISSUE TITLE
Error : <!DOCTYPE html> <meta charset="utf-8"> <body>

### ISSUE THREAD

**Issue by englianhu** [christophergandrud/d3Network#31]
I tried to plot a fancy dynamical graph since yesterday but there were error as show in attached right-hand-side panel inside RStudio picture. Anything wrong?

```
d3data %>% d3SimpleNetwork(., width=1400, height=800)
```

and plot molecule and dna shapes' fancy graph but looks like a funny output even though I set the `width='automatic'`.

```
d3data %>% as.list %>% d3Tree(., width=1400, height=800)
```

![untitled](https://cloud.githubusercontent.com/assets/7227582/10724231/24d89bc6-7c06-11e5-997b-8b57fc46ff08.jpg)

Try to run the code not in RMarkdown mode, below codes became error but its work yesterday.

``` diff
> d3data <- dfm$data %>% data.frame
- Error in eval(expr, envir, enclos) : object 'dfm' not found
> d3data$X1 <- ifelse(is.na(d3data$X1),'NA',d3data$X1)
- Error in ifelse(is.na(d3data$X1), "NA", d3data$X1) : 
-  object 'd3data' not found
> d3data %>% d3SimpleNetwork(., width=1400, height=800)
- Error in eval(expr, envir, enclos) : object 'd3data' not found
> d3data %>% as.list %>% d3Tree(., width=1400, height=800)
- Error in eval(expr, envir, enclos) : object 'd3data' not found
```

**Comment by englianhu** [comment]
Copied and paste on online html editor is works , but sounds only data frame with 2 columns while my data has 518 columns.

```
> dim(d3data)
[1] 645 518
d3data %>% d3SimpleNetwork(., width=1400, height=800)
```

![d3data-output](https://cloud.githubusercontent.com/assets/7227582/10725368/f42d7d6c-7c0e-11e5-9d8c-e7944aeacffc.jpg)

pasted the output on online html editor, from the json data we can see couple of teams' name (elements) but the output just a circle point.

```
d3data %>% as.list %>% d3Tree(., width=1400, height=800)
```

![d3tree_output](https://cloud.githubusercontent.com/assets/7227582/10725577/51bd0294-7c10-11e5-9cd7-9e5c9907f083.jpg)

**Comment by christophergandrud** [comment]
Hi, d3Network is no longer supported. Please use networkD3
