### ISSUE TITLE
Color in Sankey 

### ISSUE THREAD

**Issue by jpf5046** [christophergandrud/d3Network#32]
Check on StackOverflow and other searches--found people with the same issue, might be a bug?

http://stackoverflow.com/questions/35823962/how-to-color-groups-in-networkd3s-sankeynetwork/39208537#39208537

NodeGroup in sankeyNetwork does not plot color, but Group in forceNetwork works fine.

**Comment by christophergandrud** [comment]
Thanks for pointing this out.

Could you repost on [networkD3](https://github.com/christophergandrud/networkD3/issues) issues as d3Network is no longer supported.
